### ISSUE TITLE
non è possibile inserire le immagini dei device di grandezza superiore a 100 x100

### ISSUE THREAD

**Issue by AndreaMoriconi** [Dr-lvr/Protocol__Sim#5]
inserimento immagine 250 x 250
Descrizione: l' immagine viene caricata correttamente ma i pacchetti non riescono a circolare nella rete.

error code:

Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
	at java.util.Vector$Itr.checkForComodification(Vector.java:1212)
	at java.util.Vector$Itr.next(Vector.java:1165)
	at animation.sprites.Board.checkCollisions(Board.java:155)
	at animation.sprites.Board.actionPerformed(Board.java:101)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Dr-lvr** [comment]
Added default image scaling in Class Sprite:

protected void loadImage(String imageSource) {

        //default images scaling
        ImageIcon imageIcon = new ImageIcon(imageSource);
        if(this instanceof Device){
            image = imageIcon.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT);
            imageIcon = new ImageIcon(image);
        } else if (this instanceof Package){
            image = imageIcon.getImage().getScaledInstance(30, 18, Image.SCALE_DEFAULT);
            imageIcon = new ImageIcon(image);
        }
    }
